#Docker Compose 파일 형식의 버전을 지정합니다
version: "3.8"

services:
  #서비스 정의
  backend-blue:
    image: ${DOCKERHUB_USERNAME}/${BACKEND_IMAGE_NAME}:${BACKEND_IMAGE_TAG}
    #컨테이너 실행될 때 부여될 이름
    container_name: backend-blue
    #prod 프로필로 실행되도록 설정
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    #포트 포워딩. 외부의 8081 포트로 들어온 요청을 컨테이너 내부의 8080 포트로 전달
    ports:
      - "8081:8080"
    #DB 비번등 비밀 정보 파일 로드
    env_file:
      - .env
    #컨테이너가 충돌로 종료되거나 서버가 재부팅될 때, 도커가 자동으로 컨테이너 다시 살려낸다
    restart: always
    #특정 네트워크에 소속
    networks:
      - team6-bluegreen
    #애플리케이션 정상 작동 중인지 체크
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/api/actuator/health || exit 1" ]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 30s

  backend-green:
    image: ${DOCKERHUB_USERNAME}/${BACKEND_IMAGE_NAME}:${BACKEND_IMAGE_TAG}
    container_name: backend-green
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8082:8080"
    env_file:
      - .env
    restart: always
    networks:
      - team6-bluegreen
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/api/actuator/health || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s

#서비스를 사용할 네트워크 이름 정의
networks:
  team6-bluegreen:
    #external: true
    driver: bridge