limit_req_zone $binary_remote_addr zone=api_general:10m rate=50r/s;

server {
    listen 80;
    listen 8080;

    server_name 43.202.182.58; # 현재 EC2의 공인 IP

    client_max_body_size 500M;

    #배포 스크립트가 갈아끼우는 파일들
    #처음 실행 전 sudo touch /etc/nginx/conf.d/frontend/conf backend.conf 필수
    include /etc/nginx/conf.d/frontend.conf;
    include /etc/nginx/conf.d/backend.conf;
}