# 1. 백엔드 Green 메인 API 경로 (8082 포트)
location /api/ {
    proxy_pass http://127.0.0.1:8080;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

location /api/actuator/health {
    proxy_pass http://127.0.0.1:8080/api/actuator/health;
    access_log off;
}